spring:
  application:
    name: math

  datasource:
    url: jdbc:postgresql://localhost:5432/mathjudge
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs

api:
  jwt:
    secret: ${SECRET_KEY:supersecret}